tasks:
  # Environment preparation
  robotmk-env:
    shell: python robotmk-env.py
  # Short-Runner
  robotmk:
    shell: python robotmk.py
  # Long-Runner (async/external)
  robotmk-runner:
    shell: python robotmk-runner.py

condaConfigFile: conda.yaml
artifactsDir: output
PATH:
  - .
PYTHONPATH:
  - .
ignoreFiles:
  - .gitignore
