tasks:
  robotmk-env:
    shell: python robotmk-env.py
  robotmk-controller:
    shell: python robotmk.py

condaConfigFile: conda.yaml
artifactsDir: output
PATH:
  - .
PYTHONPATH:
  - .
ignoreFiles:
  - .gitignore
